/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedTransportersRouteImport } from './routes/_authenticated/transporters'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedDealersRouteImport } from './routes/_authenticated/dealers'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCustomersRouteImport } from './routes/_authenticated/customers'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices.index'
import { Route as AuthenticatedVendorsIdRouteImport } from './routes/_authenticated/vendors.$id'
import { Route as AuthenticatedTransportersIdRouteImport } from './routes/_authenticated/transporters.$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedDealersIdRouteImport } from './routes/_authenticated/dealers.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransportersRoute =
  AuthenticatedTransportersRouteImport.update({
    id: '/transporters',
    path: '/transporters',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealersRoute = AuthenticatedDealersRouteImport.update({
  id: '/dealers',
  path: '/dealers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCustomersRoute = AuthenticatedCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorsIdRoute = AuthenticatedVendorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVendorsRoute,
} as any)
const AuthenticatedTransportersIdRoute =
  AuthenticatedTransportersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedTransportersRoute,
  } as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealersIdRoute = AuthenticatedDealersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedDealersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/transporters': typeof AuthenticatedTransportersRouteWithChildren
  '/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/dealers/$id': typeof AuthenticatedDealersIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/transporters/$id': typeof AuthenticatedTransportersIdRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/customers': typeof AuthenticatedCustomersRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dealers': typeof AuthenticatedDealersRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/transporters': typeof AuthenticatedTransportersRouteWithChildren
  '/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/dealers/$id': typeof AuthenticatedDealersIdRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/transporters/$id': typeof AuthenticatedTransportersIdRoute
  '/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/customers': typeof AuthenticatedCustomersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dealers': typeof AuthenticatedDealersRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/_authenticated/transporters': typeof AuthenticatedTransportersRouteWithChildren
  '/_authenticated/vendors': typeof AuthenticatedVendorsRouteWithChildren
  '/_authenticated/dealers/$id': typeof AuthenticatedDealersIdRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/transporters/$id': typeof AuthenticatedTransportersIdRoute
  '/_authenticated/vendors/$id': typeof AuthenticatedVendorsIdRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/customers'
    | '/dashboard'
    | '/dealers'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/transporters'
    | '/vendors'
    | '/dealers/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/transporters/$id'
    | '/vendors/$id'
    | '/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/customers'
    | '/dashboard'
    | '/dealers'
    | '/reports'
    | '/settings'
    | '/templates'
    | '/transporters'
    | '/vendors'
    | '/dealers/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/transporters/$id'
    | '/vendors/$id'
    | '/invoices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/_authenticated/customers'
    | '/_authenticated/dashboard'
    | '/_authenticated/dealers'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/_authenticated/transporters'
    | '/_authenticated/vendors'
    | '/_authenticated/dealers/$id'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/transporters/$id'
    | '/_authenticated/vendors/$id'
    | '/_authenticated/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transporters': {
      id: '/_authenticated/transporters'
      path: '/transporters'
      fullPath: '/transporters'
      preLoaderRoute: typeof AuthenticatedTransportersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealers': {
      id: '/_authenticated/dealers'
      path: '/dealers'
      fullPath: '/dealers'
      preLoaderRoute: typeof AuthenticatedDealersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers': {
      id: '/_authenticated/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendors/$id': {
      id: '/_authenticated/vendors/$id'
      path: '/$id'
      fullPath: '/vendors/$id'
      preLoaderRoute: typeof AuthenticatedVendorsIdRouteImport
      parentRoute: typeof AuthenticatedVendorsRoute
    }
    '/_authenticated/transporters/$id': {
      id: '/_authenticated/transporters/$id'
      path: '/$id'
      fullPath: '/transporters/$id'
      preLoaderRoute: typeof AuthenticatedTransportersIdRouteImport
      parentRoute: typeof AuthenticatedTransportersRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dealers/$id': {
      id: '/_authenticated/dealers/$id'
      path: '/$id'
      fullPath: '/dealers/$id'
      preLoaderRoute: typeof AuthenticatedDealersIdRouteImport
      parentRoute: typeof AuthenticatedDealersRoute
    }
  }
}

interface AuthenticatedDealersRouteChildren {
  AuthenticatedDealersIdRoute: typeof AuthenticatedDealersIdRoute
}

const AuthenticatedDealersRouteChildren: AuthenticatedDealersRouteChildren = {
  AuthenticatedDealersIdRoute: AuthenticatedDealersIdRoute,
}

const AuthenticatedDealersRouteWithChildren =
  AuthenticatedDealersRoute._addFileChildren(AuthenticatedDealersRouteChildren)

interface AuthenticatedTransportersRouteChildren {
  AuthenticatedTransportersIdRoute: typeof AuthenticatedTransportersIdRoute
}

const AuthenticatedTransportersRouteChildren: AuthenticatedTransportersRouteChildren =
  {
    AuthenticatedTransportersIdRoute: AuthenticatedTransportersIdRoute,
  }

const AuthenticatedTransportersRouteWithChildren =
  AuthenticatedTransportersRoute._addFileChildren(
    AuthenticatedTransportersRouteChildren,
  )

interface AuthenticatedVendorsRouteChildren {
  AuthenticatedVendorsIdRoute: typeof AuthenticatedVendorsIdRoute
}

const AuthenticatedVendorsRouteChildren: AuthenticatedVendorsRouteChildren = {
  AuthenticatedVendorsIdRoute: AuthenticatedVendorsIdRoute,
}

const AuthenticatedVendorsRouteWithChildren =
  AuthenticatedVendorsRoute._addFileChildren(AuthenticatedVendorsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCustomersRoute: typeof AuthenticatedCustomersRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealersRoute: typeof AuthenticatedDealersRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedTransportersRoute: typeof AuthenticatedTransportersRouteWithChildren
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRouteWithChildren
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCustomersRoute: AuthenticatedCustomersRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealersRoute: AuthenticatedDealersRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedTransportersRoute: AuthenticatedTransportersRouteWithChildren,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRouteWithChildren,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
